spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      encoding: UTF-8

  flyway:
    enabled: true
    locations: classpath:CustomerContext/infrastructure/migration/V1__.sql
    baseline-on-migrate: true

