CREATE TABLE cart_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    cart_id     BIGINT                                  NOT NULL,
    product_id  BIGINT                                  NOT NULL,
    unit_price  DECIMAL(10, 2),
    total_price DECIMAL(10, 2),
    value       INTEGER                                 NOT NULL,
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

CREATE TABLE carts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    customer_id BIGINT                                  NOT NULL,
    items_count INTEGER                                 NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    customer_id BIGINT                                  NOT NULL,
    product_id  BIGINT                                  NOT NULL,
    is_verified BOOLEAN                                 NOT NULL,
    is_hidden   BOOLEAN                                 NOT NULL,
    content     TEXT,
    value       INTEGER,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE customers
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version        BIGINT,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    user_id        BIGINT                                  NOT NULL,
    is_active      BOOLEAN                                 NOT NULL,
    email_verified BOOLEAN                                 NOT NULL,
    phone_verified BOOLEAN                                 NOT NULL,
    first_name     VARCHAR(64)                             NOT NULL,
    last_name      VARCHAR(64)                             NOT NULL,
    middle_name    VARCHAR(64),
    email          VARCHAR(128)                            NOT NULL,
    value          VARCHAR(32)                             NOT NULL,
    street         VARCHAR(64)                             NOT NULL,
    city           VARCHAR(64)                             NOT NULL,
    state          VARCHAR(64),
    postal_code    VARCHAR(32)                             NOT NULL,
    country        VARCHAR(64)                             NOT NULL,
    apartment      VARCHAR(64),
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE favorite_products
(
    favorites_id BIGINT NOT NULL,
    product_id   BIGINT
);

CREATE TABLE favorites
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    customer_id BIGINT                                  NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_favorites PRIMARY KEY (id)
);

ALTER TABLE carts
    ADD CONSTRAINT uc_carts_customer UNIQUE (customer_id);

ALTER TABLE customers
    ADD CONSTRAINT uc_customers_email UNIQUE (email);

ALTER TABLE customers
    ADD CONSTRAINT uc_customers_userid UNIQUE (user_id);

ALTER TABLE favorites
    ADD CONSTRAINT uc_favorites_customer UNIQUE (customer_id);

ALTER TABLE carts
    ADD CONSTRAINT FK_CARTS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_CART FOREIGN KEY (cart_id) REFERENCES carts (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE favorites
    ADD CONSTRAINT FK_FAVORITES_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE favorite_products
    ADD CONSTRAINT fk_favorite_products_on_favorites FOREIGN KEY (favorites_id) REFERENCES favorites (id);